name: Test Build
on:
  push:
    branches: [ 'android-10.0' ]

  workflow_dispatch:
  watch:
    types: [started]

env:
  MANIFEST: git://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-10.0
  DEVICE: phoenix
  DT_LINK: https://github.com/hraj9258/pbrp_phoenix -b android-10.0
  DT_PATH: device/xiaomi/phoenix
  CHAT_ID: ${{ secrets.BOT_CHAT_ID }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  TARGET: recoveryimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Recovery Compilation
         uses: Area69Lab/Recovery-Compiler@production
    env:
      MANIFEST: "Recovery Manifest URL with -b branch"
      DT_LINK: "https://github.com/PitchBlackRecoveryProject/android_device_xiaomi_phoenix-pbrp"
      VENDOR: "xiaomi"
      CODENAME: "phoenix"
      KERNELISPREBUILT: "true"
      TARGET: "recoveryimage"
      FLAVOR: "eng"
      TZ: "Asia/Kolkata"
