name: Test Build
on:
  push:
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Recovery Compilation
         if: false
         uses: Carbonatedblack/Recovery-Compiler@production
         env:
           MANIFEST: "https://github.com/PitchBlackRecoveryProject/manifest_pb -b android-10.0"
           DT_LINK: "https://github.com/PitchBlackRecoveryProject/android_device_xiaomi_phoenix-pbrp"
           VENDOR: "xiaomi"
           CODENAME: "phoenix"
           KERNELISPREBUILT: "true"
           TARGET: "recoveryimage"
           FLAVOR: "eng"
           TZ: "Asia/Kolkata"
           
       - name: Mock Build
         if: true
         run: |
          # Mock Official Build
          touch work/out/target/product/phoenix/PBRP-RMX1941-3.0.0-20210214-2119-OFFICIAL.zip
          touch work/out/target/product/phoenix/recovery.img

       - name: Release Builds
         uses: "marvinpinto/action-automatic-releases@latest"
         with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "CI"
          files: |
              work/out/target/product/*/*.zip
              work/out/target/product/*/*.img
