name: Test Build
on:
  push:
    branches: [ 'android-10.0' ]

  workflow_dispatch:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Recovery Compilation
         uses: Area69Lab/Recovery-Compiler@production
    env:
      MANIFEST: "Recovery Manifest URL with -b branch"
      DT_LINK: "https://github.com/PitchBlackRecoveryProject/android_device_xiaomi_phoenix-pbrp"
      VENDOR: "xiaomi"
      CODENAME: "phoenix"
      KERNELISPREBUILT: "true"
      TARGET: "recoveryimage"
      FLAVOR: "eng"
      TZ: "Asia/Kolkata"
