name: Test Build
on:
  push:
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Recovery Compilation
         uses: Area69Lab/Recovery-Compiler@beta
         env:
           MANIFEST: "https://github.com/PitchBlackRecoveryProject/manifest_pb -b android-10.0"
           DT_LINK: "https://github.com/PitchBlackRecoveryProject/android_device_xiaomi_phoenix-pbrp"
           VENDOR: "xiaomi"
           CODENAME: "phoenix"
           KERNELISPREBUILT: "true"
           TARGET: "recoveryimage"
           FLAVOR: "eng"
           TZ: "Asia/Kolkata"

       - uses: "marvinpinto/action-automatic-releases@latest"
         with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            work/out/target/product/*/*.zip
