name: Test Build
on:
  push:
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Recovery Compilation
         uses: Area69Lab/Recovery-Compiler@beta
         env:
           MANIFEST: "https://github.com/PitchBlackRecoveryProject/manifest_pb -b android-10.0"
           DT_LINK: "https://github.com/PitchBlackRecoveryProject/android_device_xiaomi_phoenix-pbrp"
           VENDOR: "xiaomi"
           CODENAME: "phoenix"
           KERNELISPREBUILT: "true"
           TARGET: "recoveryimage"
           FLAVOR: "eng"
           TZ: "Asia/Kolkata"

       - name: Generate build number
         id: buildnumber
         uses: einaregilsson/build-number@v3 
         with:
          token: ${{secrets.github_token}}

       - uses: "marvinpinto/action-automatic-releases@latest"
         with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{needs.build.outputs.build_number}}"
          prerelease: false
          title: "CI"
          files: |
              work/out/target/product/${{ env.CODENAME }}/*.zip
              work/out/target/product/${{ env.CODENAME }}/recovery.img
              work/out/target/product/${{ env.CODENAME }}/boot.img
