name: Test Build
on:
  push:
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: export PATHS
         run: |
           echo "/usr/local/bin" >> $GITHUB_PATH
           echo "/home/runner/bin" >> $GITHUB_PATH
       - name: Recovery Compilation
         uses: Area69Lab/Recovery-Compiler@beta
         env:
           MANIFEST: "https://github.com/PitchBlackRecoveryProject/manifest_pb -b android-10.0"
           DT_LINK: "https://github.com/PitchBlackRecoveryProject/android_device_xiaomi_phoenix-pbrp"
           VENDOR: "xiaomi"
           CODENAME: "phoenix"
           KERNELISPREBUILT: "true"
           TARGET: "recoveryimage"
           FLAVOR: "eng"
           TZ: "Asia/Kolkata"
       - uses: actions/upload-artifact@v2
         with:
          name: ${{ env.CODENAME }}_${{ env.TARGET }}-zip
          path: work/out/target/product/*/*.zip

