name: PBRP CI/CD
on:
  push:
  workflow_dispatch:
    inputs:
      DEPLOY_TYPE:
        description: 'Deploy Type (TEST/BETA/OFFICIAL)'
        required: true
        default: 'TEST'
  watch:
    types: [started]

env:
  BUILD_RELEASE_TYPE: "TEST"
  MANIFEST: "https://github.com/PitchBlackRecoveryProject/manifest_pb -b android-10.0"
  BOT_API: ${{ secrets.BOT_API }}
  GCF_AUTH_KEY: ${{ secrets.GCF_AUTH_KEY }}
  GH_BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GitHubMail: ${{ secrets.GitHubMail }}
  GitHubName: ${{ secrets.GitHubName }}
  SFPassword: ${{ secrets.SFPassword }}
  SFUserName: ${{ secrets.SFUserName }}

jobs:
  PBRP_CI:
    runs-on: ubuntu-latest

    steps:
       - name: Cleaning Up Runner
         uses: rokibhasansagar/slimhub_actions@main

       - name: Recovery Compilation and Release
         uses: Carbonatedblack/Recovery-Compiler@beta
       
       - name: Release Builds 
         run: |
              [[ ! -z ${{ github.event.inputs.DEPLOY_TYPE }} ]] && BUILD_RELEASE_TYPE=${{ github.event.inputs.DEPLOY_TYPE }}
              sudo apt-get update && sudo apt-get install sshpass -y
              export CIRCLE_SHA1=$GITHUB_SHA
              cd $BuildPath
              bash vendor/utils/pb_deploy.sh ${BUILD_RELEASE_TYPE} ${VENDOR} ${CODENAME}              
