name: PBRP ci
on:
  push:
  workflow_dispatch:
  watch:
    types: [started]

env:
  VENDOR: "xiaomi"
  CODENAME: "phoenix"
  BUILD_RELEASE_TYPE: "TEST"
  TARGET: "recoveryimage"
  FLAVOR: "eng"
  MANIFEST: "https://github.com/PitchBlackRecoveryProject/manifest_pb -b ${GITHUB_REF#refs/heads/}"
  DT_LINK: "https://github.com/${GITHUB_REPOSITORY} -b ${GITHUB_REF#refs/heads/}"
  TZ: "Asia/Kolkata"
  BOT_API: ${{ secrets.BOT_API }}
  GCF_AUTH_KEY: ${{ secrets.GCF_AUTH_KEY }}
  GH_BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GitHubMail: ${{ secrets.GitHubMail }}
  GitHubName: ${{ secrets.GitHubName }}
  SFPassword: ${{ secrets.SFPassword }}
  SFUserName: ${{ secrets.SFUserName }}

jobs:
  compilation:
    runs-on: ubuntu-20.04

    steps:
       - name: Recovery Compilation
         uses: Carbonatedblack/Recovery-Compiler@production
         
       - name: Release Builds
         run: |
              sudo apt-get install sshpass -y
              export CIRCLE_SHA1=$GITHUB_SHA
              cd work
              bash vendor/utils/pb_deploy.sh ${BUILD_RELEASE_TYPE} ${VENDOR} ${CODENAME}
              
