name: PBRP CI/CD
on:
  push:
  workflow_dispatch:
  watch:
    types: [started]

env:
  BUILD_RELEASE_TYPE: "TEST"
  TARGET: "recoveryimage"
  FLAVOR: "eng"
  MANIFEST: "https://github.com/PitchBlackRecoveryProject/manifest_pb"
  TZ: "Asia/Kolkata"
  BOT_API: ${{ secrets.BOT_API }}
  GCF_AUTH_KEY: ${{ secrets.GCF_AUTH_KEY }}
  GH_BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GitHubMail: ${{ secrets.GitHubMail }}
  GitHubName: ${{ secrets.GitHubName }}
  SFPassword: ${{ secrets.SFPassword }}
  SFUserName: ${{ secrets.SFUserName }}

jobs:
  compilation:
    runs-on: ubuntu-20.04

    steps:
       - name: Cleaning Up Runner
         uses: rokibhasansagar/slimhub_actions@main

       - name: Recovery Compilation and Release
         uses: Carbonatedblack/Recovery-Compiler@production
         run: |
              sudo apt-get update && sudo apt-get install sshpass -y
              export CIRCLE_SHA1=$GITHUB_SHA
              cd work
              bash vendor/utils/pb_deploy.sh ${BUILD_RELEASE_TYPE} ${VENDOR} ${CODENAME}              
